feat: Adicionando pesquisa de usuario na header e na pagina de pesquisa
lucasfirmo62/MovieReview pull request #135
Opened 2023-05-09 13:44 UTC by lucasfirmo62

## O que foi feito?

Primeiramente foi adicionado dois radio para selecionar que tipo de pesquisa o usuário quer fazer
![image](https://github.com/lucasfirmo62/MovieReview/assets/58527718/5167bcc0-dd67-4ada-aca2-3cd5eec23516)
Selecionando a opção usuário para fazer a pesquisa
![image](https://github.com/lucasfirmo62/MovieReview/assets/58527718/063ef336-1397-41cd-8df8-8adbda4ea0ba)

Depois foi inserido paginações diferentes, caso ele selecione o usuário para pesquisar, ele irá pesquisar o usuário
![image](https://github.com/lucasfirmo62/MovieReview/assets/58527718/2a390a31-13be-48c6-a8cf-daed4c122fc5)

2023-05-09 15:54 UTC, Patriarka requested changes
Olá, Lucas!

Gostaria de compartilhar algumas observações em relação à opção de pesquisa no menu da header. Em primeiro lugar, acredito que o radio button utilizado não esteja muito estético e possa confundir alguns usuários. Além disso, a cor preta da letra no radio button não contrasta bem com o fundo escuro, o que dificulta a leitura.

Outro ponto a ser considerado é a falta de responsividade da opção, que torna difícil selecioná-la em dispositivos móveis. Nesse sentido, gostaria de sugerir que os radios sejam substituídos por botões ao lado ou um menu de opções, como exemplificado na imagem abaixo:

![image](https://github.com/lucasfirmo62/MovieReview/assets/53534886/237f543b-acf7-4aa7-aa04-9f98f6ae1c8c)

Além de que, o botão acaba passando o limite da tela para telas com width menor do que 500px.
![image](https://github.com/lucasfirmo62/MovieReview/assets/53534886/f8867197-a15e-4cdd-a35c-e14d6cd5b6ef)

Ademais, o botão em questão pode ser difícil de clicar em dispositivos móveis, mesmo sendo um radio.

2023-05-09 20:12 UTC, lucasfirmo62 commented
## O que foi feito?
Foram aplicadas alterações exigidas
![image](https://github.com/lucasfirmo62/MovieReview/assets/58527718/77d3f8f3-5259-4688-a2f3-2ac24f876dd1)
![image](https://github.com/lucasfirmo62/MovieReview/assets/58527718/9bf383f6-06a1-42e3-9f75-fed5bfd7d5a3)

2023-05-09 20:30 UTC, Patriarka requested changes
Primeiramente, parabéns por ter resolvido o problema de responsividade! No entanto, ainda há algumas questões a serem resolvidas em relação à usabilidade.

Os botões parecem estar muito dispersos na tela, o que pode dar a impressão de que eles não fazem parte do mesmo conjunto de seleção. Além disso, as cores podem estar difíceis de enxergar, mas isso pode ser devido à minha tela. Se puder olhar cuidadosamente a questão das cores para garantir que elas sejam legíveis para todos os usuários.

Outra questão é que o conteúdo parece estar se sobrepondo ao meio, como mostrado na imagem abaixo. Isso pode estar ocasionando um bug ao selecionar a opção "filmes". Para resolver isso, podemos ajustar a disposição do conteúdo na página para garantir que cada elemento tenha seu próprio espaço adequado.
![image](https://github.com/lucasfirmo62/MovieReview/assets/53534886/aa4b9039-3f62-4244-94e2-c8218bb3fcd2)

Outra questão que esqueci de avaliar na minha primeira revisão e peço desculpas é que o ícone da barra de pesquisar parece ter sumido do input de pesquisa. Tal como havia sido implementado no pull request #74. Além de ser necessário alterar o texto do placeholder do input.

![image](https://github.com/lucasfirmo62/MovieReview/assets/53534886/0683e1bf-8ca8-45f2-82d5-d7260f9d054e)

2023-05-11 16:12 UTC, lucasfirmo62 commented
## O que foi feito?

foi corrigido "problemas" exigidos

![image](https://github.com/lucasfirmo62/MovieReview/assets/58527718/2d08cdbe-e81e-4426-8f15-0a311220d299)
![image](https://github.com/lucasfirmo62/MovieReview/assets/58527718/bf56048f-5254-4cd5-93be-dff872b5a9d2)
![image](https://github.com/lucasfirmo62/MovieReview/assets/58527718/990467b3-248d-4e1d-92c4-9fac6e4a37eb)

2023-05-13 19:41 UTC, lucasfirmo62 commented
## O que foi feito?

Foi incorporado a estilização exigida
![image](https://github.com/lucasfirmo62/MovieReview/assets/58527718/020d4a7a-fa81-4cf5-a4c3-d12ae5cd4356)
![image](https://github.com/lucasfirmo62/MovieReview/assets/58527718/13a000a2-fcc7-4aea-8b4c-daa1302168ea)
![image](https://github.com/lucasfirmo62/MovieReview/assets/58527718/35c1cb39-dfd7-4a38-83d5-944511ea9d41)

2023-05-18 10:53 UTC, Patriarka approved these changes
Parabéns, Lucas! Acredito que com as alterações propostas aqui podem ser aceitas para o merge subsequente.

2023-05-18 10:54 UTC, merged