143 favoritar filmes
lucasfirmo62/MovieReview pull request #159
Opened 2023-05-13 22:13 UTC by matchur

##O que foi feito?
Foi criado o botão para favoritar um filme 
![image](https://github.com/lucasfirmo62/MovieReview/assets/22385995/cb954b7c-4ae5-4e6a-94a9-4f4a5371420c)
e uma função que é inicializada ao clicar 
![image](https://github.com/lucasfirmo62/MovieReview/assets/22385995/755cb833-90b1-45de-aeec-1a1869cdf155)

2023-05-13 22:54 UTC, Patriarka commented on myfrontend/src/api.js
> +  baseURL: 'https://vertuz.pythonanywhere.com/',
Só alterar a baseURL para 'http://localhost:8000' para os 3 casos no arquivo api.js

2023-05-13 22:54 UTC, Patriarka commented on myfrontend/src/api.js
> +        await axios.post('https://vertuz.pythonanywhere.com/api/token/verify/', { token: access }, { headers });
aqui também

2023-05-13 22:54 UTC, Patriarka commented on myfrontend/src/api.js
> +            const response = await axios.post('https://vertuz.pythonanywhere.com/api/token/refresh/', { refresh: refresh }, { headers });
e aqui

2023-05-13 22:55 UTC, Patriarka requested changes
Olá, Matheus. Acredito que após a mudança sugerida o seguinte Pull Request estará pronto para o merge.

2023-05-21 01:30 UTC, gustavofavaro approved these changes
Tudo certo! Apenas uma sugestão: mudar o texto do botão para "Desfavoritar" ou algo assim para fazer com que o usuário entenda que o filme já esteja marcado como favorito e se ele deseja desmarcar. Isto pode ser incluído na etapa de integração desta funcionalidade.

2023-05-22 11:20 UTC, Patriarka approved these changes

2023-05-22 11:21 UTC, merged